### ISSUE TITLE
下载出错（附报错信息）

### ISSUE THREAD

**Issue by lovecn** [lonsty/weibo-image-spider#12]
```js
λ python main.py -u 3261134763
[2021-10-13 17:03:03,984 MainThread              ERROR  48] Weibo website structure updated, please add a issue to https://github.com/lonsty/weibo-image-spider/issues., Retrying in 1 seconds...
[2021-10-13 17:03:05,031 MainThread              ERROR  48] Weibo website structure updated, please add a issue to https://github.com/lonsty/weibo-image-spider/issues., Retrying in 2 seconds...
Traceback (most recent call last):
  File "d:\code\weibo-image-spider\weibo_image_spider\spider_workers.py", line 36, in query_user_by_name
    host = first.find("a", class_="name").get("href")
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\weibo-image-spider\main.py", line 6, in <module>
    weibo_command()
  File "E:\python\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "E:\python\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "E:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\python\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "d:\code\weibo-image-spider\weibo_image_spider\cli.py", line 75, in weibo_command
    const.user = query_user_by_name(const)
  File "d:\code\weibo-image-spider\weibo_image_spider\utils.py", line 54, in f_retry
    return f(*args, **kwargs)
  File "d:\code\weibo-image-spider\weibo_image_spider\spider_workers.py", line 40, in query_user_by_name
    raise ContentParserError(
weibo_image_spider.exceptions.ContentParserError: Weibo website structure updated, please add a issue to https://github.com/lonsty/weibo-image-spider/issues.
```

**Comment by lonsty** [comment]
Duplicate of #10 
#13 已修复
